/* Formatted on 05/03/2018 09:36:30 p.m. (QP5 v5.300) */
CREATE TABLE NOBEL.BIRTHPLACE
(
    BIRTHPLACE_ID   NUMBER,
    BIRTHPLACE      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.CAMPO
(
    CAMPO_ID   NUMBER,
    CAMPO      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.CATEGORIA
(
    CATEGORIA_ID   NUMBER,
    CATEGORIA      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.COUNTRY
(
    COUNTRY_ID   NUMBER,
    COUNTRY      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.INTER_CAMPO
(
    PREMIO_ID   NUMBER,
    CAMPO_ID    NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.INTER_PREMIO
(
    INTER_PREMIO_ID   NUMBER,
    USER_ID           NUMBER,
    PREMIO_ID         NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.PREMIO
(
    PREMIO_ID      NUMBER,
    YEAR           DATE,
    MOTIVACION     NVARCHAR2 (250),
    CATEGORIA_ID   NUMBER,
    COUNTRY_ID     NUMBER,
    NOMBRE         NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.RESIDENCIA
(
    RESIDENCIA_ID   NUMBER,
    RESIDENCIA      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.RESIDENCIA_INTER
(
    PREMIO_ID       NUMBER,
    RESIDENCIA_ID   NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.ROLES
(
    ROLE_ID   NUMBER,
    ROLE      NVARCHAR2 (250)
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE TABLE NOBEL.USUARIOS
(
    USER_ID         NUMBER,
    NOMBRE          NVARCHAR2 (250),
    BIRTHDAY        DATE,
    BIRTHPLACE_ID   NUMBER,
    ROL_ID          NUMBER
)
TABLESPACE SYSTEM
PCTUSED 40
PCTFREE 10
INITRANS 1
MAXTRANS 255
STORAGE (INITIAL 64 K
         NEXT 1 M
         MINEXTENTS 1
         MAXEXTENTS UNLIMITED
         PCTINCREASE 0
         FREELISTS 1
         FREELIST GROUPS 1
         BUFFER_POOL DEFAULT)
LOGGING
NOCOMPRESS
NOCACHE
MONITORING;


CREATE UNIQUE INDEX NOBEL.BIRTHPLACE_PK
    ON NOBEL.BIRTHPLACE (BIRTHPLACE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.CAMPO_PK
    ON NOBEL.CAMPO (CAMPO_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.CATEGORIA_PK
    ON NOBEL.CATEGORIA (CATEGORIA_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.COUNTRY_PK
    ON NOBEL.COUNTRY (COUNTRY_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.INTER_PREMIO_PK
    ON NOBEL.INTER_PREMIO (INTER_PREMIO_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.PREMIO_PK
    ON NOBEL.PREMIO (PREMIO_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.RESIDENCIA_PK
    ON NOBEL.RESIDENCIA (RESIDENCIA_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.ROLES_PK
    ON NOBEL.ROLES (ROLE_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

CREATE UNIQUE INDEX NOBEL.USUARIOS_PK
    ON NOBEL.USUARIOS (USER_ID)
    LOGGING
    TABLESPACE SYSTEM
    PCTFREE 10
    INITRANS 2
    MAXTRANS 255
    STORAGE (INITIAL 64 K
             NEXT 1 M
             MINEXTENTS 1
             MAXEXTENTS UNLIMITED
             PCTINCREASE 0
             FREELISTS 1
             FREELIST GROUPS 1
             BUFFER_POOL DEFAULT);

ALTER TABLE NOBEL.BIRTHPLACE ADD (
  CONSTRAINT BIRTHPLACE_PK
  PRIMARY KEY
  (BIRTHPLACE_ID)
  USING INDEX NOBEL.BIRTHPLACE_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.CAMPO ADD (
  CONSTRAINT CAMPO_PK
  PRIMARY KEY
  (CAMPO_ID)
  USING INDEX NOBEL.CAMPO_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.CATEGORIA ADD (
  CONSTRAINT CATEGORIA_PK
  PRIMARY KEY
  (CATEGORIA_ID)
  USING INDEX NOBEL.CATEGORIA_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.COUNTRY ADD (
  CONSTRAINT COUNTRY_PK
  PRIMARY KEY
  (COUNTRY_ID)
  USING INDEX NOBEL.COUNTRY_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.INTER_PREMIO ADD (
  CONSTRAINT INTER_PREMIO_PK
  PRIMARY KEY
  (INTER_PREMIO_ID)
  USING INDEX NOBEL.INTER_PREMIO_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.PREMIO ADD (
  CONSTRAINT PREMIO_PK
  PRIMARY KEY
  (PREMIO_ID)
  USING INDEX NOBEL.PREMIO_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.RESIDENCIA ADD (
  CONSTRAINT RESIDENCIA_PK
  PRIMARY KEY
  (RESIDENCIA_ID)
  USING INDEX NOBEL.RESIDENCIA_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.ROLES ADD (
  CONSTRAINT ROLES_PK
  PRIMARY KEY
  (ROLE_ID)
  USING INDEX NOBEL.ROLES_PK
  ENABLE VALIDATE);

ALTER TABLE NOBEL.USUARIOS ADD (
  CONSTRAINT USUARIOS_PK
  PRIMARY KEY
  (USER_ID)
  USING INDEX NOBEL.USUARIOS_PK
  ENABLE VALIDATE);

--constraints

ALTER TABLE nobel.premio
    ADD CONSTRAINT FK_premio02 FOREIGN KEY (categoria_id)
        REFERENCES nobel.categoria (categoria_id)
        ENABLE VALIDATE;

ALTER TABLE nobel.inter_premio
    ADD CONSTRAINT FK_premio03 FOREIGN KEY (premio_id)
        REFERENCES NOBEL.premio (premio_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.RESIDENCIA_INTER
    ADD CONSTRAINT FK_premio04 FOREIGN KEY (premio_id)
        REFERENCES NOBEL.premio (premio_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.inter_campo
    ADD CONSTRAINT FK_premio05 FOREIGN KEY (premio_id)
        REFERENCES NOBEL.premio (premio_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.inter_campo
    ADD CONSTRAINT FK_campo01 FOREIGN KEY (campo_id)
        REFERENCES NOBEL.campo (campo_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.inter_premio
    ADD CONSTRAINT FK_users01 FOREIGN KEY (user_id)
        REFERENCES NOBEL.usuarios (user_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.usuarios
    ADD CONSTRAINT FK_users02 FOREIGN KEY (birthplace_id)
        REFERENCES NOBEL.birthplace (birthplace_id)
        ENABLE VALIDATE;


ALTER TABLE NOBEL.residencia_inter
    ADD CONSTRAINT FK_res01 FOREIGN KEY (residencia_id)
        REFERENCES NOBEL.residencia (residencia_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.roles
    ADD CONSTRAINT FK_users04 FOREIGN KEY (rol_id)
        REFERENCES NOBEL.usuarios (rol_id)
        ENABLE VALIDATE;

ALTER TABLE nobel.premio
    ADD CONSTRAINT FK_premio01 FOREIGN KEY (country_id)
        REFERENCES nobel.country (country_id)
        ENABLE VALIDATE;

ALTER TABLE NOBEL.usuarios
    ADD CONSTRAINT FK_users04 FOREIGN KEY (rol_id)
        REFERENCES NOBEL.roles (rol_id)
        ENABLE VALIDATE;